# This file was autogenerated in src/version_git.jl
immutable GitVersionInfo
    commit::AbstractString
    commit_short::AbstractString
    branch::AbstractString
    build_number::Int
    date_string::AbstractString
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
end

const GIT_VERSION_INFO = GitVersionInfo(
    "1b748f2de3d40c809ed3291cc2ddb6e381f1c383",
    "1b748f2*",
    "master",
    0,
    "2015-02-13 11:37 UTC",
    true,
    0,
    1423827427.
)
