# This file was autogenerated in src/version_git.jl
immutable GitVersionInfo
    commit::AbstractString
    commit_short::AbstractString
    branch::AbstractString
    build_number::Int
    date_string::AbstractString
    tagged_commit::Bool
    fork_master_distance::Int
    fork_master_timestamp::Float64
end

const GIT_VERSION_INFO = GitVersionInfo(
    "8e92541a5f5c7c3b2eae117a0b9daa471009d3a6",
    "8e92541*",
    "master",
    1,
    "2015-02-13 11:47 UTC",
    false,
    0,
    1423828038.
)
